### ISSUE TITLE
Class ISPAPI\I18n is already in use

### ISSUE THREAD

**Issue by fastsui** [hexonet/whmcs-ispapi-domainchecker#104]
Error Message:
Whoops\Exception\ErrorException: Cannot declare class ISPAPI\I18n, because the name is already in use in /home/managerf/public_html/modules/addons/ispapidomaincheck/lib/Common/i18n.class.php:9
Stack trace:
#0 /home/managerf/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(1, 'Cannot declare ...', '/home/managerf/...', 9)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by domainregistrar** [comment]
Did you overwrite the files instead of replacing the module?

I found removing the previous module before uploading the new one resolved
this issue.

**Comment by fastsui** [comment]
Thanks for the Information. Your Solution works for me.  But when the Solution is so easy why do you not insert this in the Documentation ?

**Comment by papakai** [comment]
@domainregistrar thanks for helping, Dude :-)

@fastsui 
We internally have symbolic links in use while developping and also on our test servers. That's the reason why we won't run into such issues. I'll extend the documentation to first delete the old module contents before unpacking the new contents. We have further plans/projects in queue that will solve such issues  directly. It just needs time when we get there.

Thanks for getting in touch with us and for bringing this up.

**Comment by papakai** [comment]
I'm decided to leave this open until we have realised that project, so that we can follow-up.

**Comment by papakai** [comment]
We have plans for 2021 to work on a new API that is thought to improve a lot of things especially in direction of 3rd-party software integrations (whmcs, blesta, ...) e.g. minimizing amount of module upgrades etc.. When this API is ready and our modules are refactored, we will have such translations probably available over our API. Therefore I am closing this issue.
