### ISSUE TITLE
No domain syn ..

### ISSUE THREAD

**Issue by hilbily852** [hexonet/whmcs-ispapi-domainchecker#120]
Have followed set up  fully the registrar works fine and says connected. Selected the domains and prices etc and using lookup from hexonet but when I try to perform a tld search it says in progress..the clogs spin but then stays on same page and does not appear to do anything or produce a error ..

**Comment by papakai** [comment]
We know the domainchecker to be working for several customers. We will come there for you too :-)

Could you please provide some Details about your setup? Which OS, whmcs version in use? Which forwarding solution used? Do you have a show case for us available? What does the browser console show - are there errors?

Thanks so much!

**Comment by hilbily852** [comment]
Porblem fixed was over php mem limit added max but also had to up max mem limit to 128M in phpe.ini and works fine 

Sorry thank you

**Comment by papakai** [comment]
np, you're always welcome.
