### ISSUE TITLE
Support WHMCS Variable $carttpl

### ISSUE THREAD

**Issue by scysys** [hexonet/whmcs-ispapi-domainchecker#121]
**Describe the bug**
$carttpl was not supported which was used in whmcs orderforms.

**To Reproduce**
Not with an default WHMCS Installation. It´s an custom Theme with mulltiple header / footer parts. Header / Footer were differently set on each template.

**Expected behavior**
Support the output of WHMCS Standard Variable $carttpl which is the orderform name.

**Screenshots**
<img width="1411" alt="Bildschirmfoto 2020-09-10 um 14 49 36" src="https://user-images.githubusercontent.com/1695531/92731210-165ae400-f375-11ea-8285-89e257229276.png">

**Version**
ISPAPI HP DomainChecker: 12.0.5
WHMCS: 7.10.2

**Comment by scysys** [comment]
Example from another template. The only way to do what i want is change the $carttpl with the hardcoded name. But this should not be an solution :)

![Bildschirmfoto 2020-09-10 um 14 56 32](https://user-images.githubusercontent.com/1695531/92731864-ef50e200-f375-11ea-8369-9c2257c7308a.png)

**Comment by papakai** [comment]
Let me know if that helped @scysys

**Comment by scysys** [comment]
Sorry, but this is not working. Same empty // activity log output.
I tried a little bit myself and dont found an way for now.

The only way that is possible with our theme is to update the orderform templates in this way 
```
{if empty($carttpl)}
{include file="orderforms/$template/header/header-part1.tpl"} 
{else}
{include file="orderforms/$carttpl/header/header-part1.tpl"}
{/if}
```
Not an big deal if you dont find a way.

**Comment by papakai** [comment]
I'll continue working on this, but first I'll have to continue with project in work/queued. I'll keep you posted.

**Comment by papakai** [comment]
Just an question - you're checking with "empty" for the existance. Can you tell me if that var is just empty or really not existing? `isset` vs `empty`.

**Comment by scysys** [comment]
carttpl is really not exist. I checked it over the smarty {debug} output.
Leave time, i dont think there are much users with such an problem / request.

Until you have an solution i found that this should be the best for my scenario
`{assign var='carttpl' value='templatename'}`

**Comment by papakai** [comment]
Give 12.0.7 a try, will be out in short. release process is running.
