### ISSUE TITLE
does not display correct prices from client group

### ISSUE THREAD

**Issue by jmmmagalhaes** [hexonet/whmcs-ispapi-domainchecker#128]
If the customer is logged in and when there are several "Client Groups" with prices different from the base, the results in the domain search are not shown the correct prices for the domains of the group in which the customer is associated, always showing the prices of the main group

**Comment by papakai** [comment]
@jmmmagalhaes thanks for reporting. I'll dive into that issue immediately.

**Comment by papakai** [comment]
@jmmmagalhaes I've been in touch with WHMCS Support to clarify next steps to find the right way to get this solved.
Please give version 13.0.3 a try - this should do it. If not or if there's still something wrong, just follow-up/reopen.

**Comment by jmmmagalhaes** [comment]
@papakai Thanks. Working Great

**Comment by papakai** [comment]
@jmmmagalhaes Great to hear. You're always welcome - You can also address Feature Requests / Ideas in here.
