### ISSUE TITLE
mydomainchecker.php setting window disappeared

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-domainchecker#130]
**Describe the bug**

**To Reproduce**
1. Go to mydomainchecker.php?language=english
2. Click on setting

**Expected behavior**
setting disappeared

**Context (please complete the following information):**
 - Device: all

 - Browser all
 - WHMCS Version: 8.1.3
 - PHP Version 7.4 - 7.3
 - ISPAPI Domainchecker Module Version: 13.0.4, 2021-03-05

**Comment by papakai** [comment]
Hi @HamidRadmani,

could you provide a screenshot to me? That would probably explain it better, I am unsure if I can follow you correctly.
From which version have you upgraded? Could you please clear browser cache and check this again (Incognito Mode would do it too)?

**Comment by HamidRadmani** [comment]
https://www.persishost.ir/members/mydomainchecker.php?language=english

**Comment by papakai** [comment]
Hey @HamidRadmani 

thanks for sharing, reproducable there.
What template are you using for the client area/cart?

Thanks!

**Comment by HamidRadmani** [comment]
I use templates/twenty-one

the new template for whmcs 8.

**Comment by HamidRadmani** [comment]
Now I test with template SIX and work well without disappearing.

the problem rise when I use twenty-one.

**Comment by papakai** [comment]
Not that easy to make a module bootstrap 3 (six) and bootstrap 4 (twenty-one) compatible without quirks :-(
No idea why WHMCS gone that way. imho they should have dropped bootstrap 3 completely, also in them six to drive everything in direction of bootstrap 4.

Anyways - thanks for forwarding. Patched in [v13.0.5](https://github.com/hexonet/whmcs-ispapi-domainchecker/raw/master/whmcs-ispapi-domainchecker-latest.zip).

**Comment by HamidRadmani** [comment]
Thank you for your fast response 🌹😊
