### ISSUE TITLE
TLD Result Order

### ISSUE THREAD

**Issue by domainregistrar** [hexonet/whmcs-ispapi-domainchecker#27]
Unfortunately the module doesn't seem to respect the order as set against each TLD in the WHMCS database, this results in the search results returning Adult domains by default at the top of the list - not necessarily the best thing.

It would be preferable for the module to respect the display order set in WHMCS (to avoid duplicate configuration).

**Comment by papakai** [comment]
Dear @domainregistrar 

Thanks for creating this issue, we will follow-up tomorrow as our lead developer is in holiday today.
In the meanwhile, please be so kind and provide us further details:
* PHP Version in use
* WHMCS Version in use
* ISPAPI HP Domainchecker Module Version in use

If possible, some screenshots showing this issue (and if possible also your configuration) would also help us to reproduce things much faster.

Thanks so much

Kai

**Comment by papakai** [comment]
Dear @domainregistrar 

I've been in talk with our lead developer. The reason of the described behavior is the domain name suggestion feature, that you can activate or deactivate in the whois provider configuration by the appropriate checkbox. In case that feature is active, we just display that generated list unchanged and thus it does not match the configured tld order. We get that generated list from our backend system API which already applies a default sorting based on internal criteria. This is the main reason why we have not thought about rewriting it again.
If you deactivate that feature, it follows the configured tld order, but without having domain name suggestions.

We will discuss this behavior internally to follow-up next year.

Thanks for bringing this up! We leave this issue open as reminder.

Kai

**Comment by domainregistrar** [comment]
Hi @papakai 

I'm not sure that's the case as I have suggestions disabled - unfortunately the suggestions were simply too off-the-wall to add value based on our tests.

It appears the results are roughly in line with the categories lists - as Adult domains are always first in the list, but there is a little movement in the order (when search for string with no extension to be clear) and a quick look at the code seems to show it's not actually doing any ordering, just pulling the TLDs from the DB and running checks (which would appear to explain the rough ordering from MySQL).

I think this may be more of a feature request than a bug to be honest, but if there is something there which is supposed to be managing the order - it could definitely be improved.

**Comment by papakai** [comment]
Thanks for the follow-up, we will have an eye on this.

**Comment by papakai** [comment]
Hey @domainregistrar 

You can check the incoming new release (we have the domain name suggestions activated) at https://try-whmcs.hexonet.net 

We will switch domain name suggestions off there on friday.

In future we plan to also provide admin area access to customers so that they can also play around with settings and the latest changes there. In the upcoming domainchecker release, the admin area has improved a lot.

**Comment by domainregistrar** [comment]
> Hey @domainregistrar
> 
> You can check the incoming new release (we have the domain name suggestions activated) at https://try-whmcs.hexonet.net (auth -> user: demo, password: demo)
> 
> We will switch domain name suggestions off there on friday.
> 
> In future we plan to also provide admin area access to customers so that they can also play around with settings and the latest changes there. In the upcoming domainchecker release, the admin area has improved a lot.

The results there seem to be significantly better! - Although doesn't work over https:// had to drop the s as timeout with https...

**Comment by papakai** [comment]
Hm, looks like that's my fault and that instance only runs on HTTP. One reason more to review that setup.

**Comment by rocketdomains** [comment]
Hey Kai!

Great work, Sir! Gotta love your new design and elements especially the "show available only" option. Here's our feedback:

1) the domain suggestions take the user away from his desired keyword which may be available in other extensions. We think User is better off seeing his keyword in all extensions first and foremost. There should be a button for the user to enable/disable suggestions.

2) "Use my IP" option does not appear to do anything. What is its function please?

3) We didn't notice any speed improvements. Is this new interface superior to the older one in terms of speed?

Warm regards,
Frazer

**Comment by papakai** [comment]
@rocketdomains / Frazer,

Thanks a lot for that feedback. Especially point 1 leads me back to some thoughts that I already had months ago: Why don't we combine the default search (keyword with just the different TLDs) and the domain name suggestions somehow.
Currently this can be toggled in the admin area by configuring the lookup registrar, if you want to get domain name suggestions or just the keyword with different tlds as list.

Point 2: "Use my IP" will use customers remote ip address to improve localization of the domain name suggestions. So if the IP belongs to a region in / or country CA, it gives domain name results near that region higher priority. The same applies to the language setting. I also recognized that using language results in better results compared to the ip address one. I can forward this to the devs.

Point 3: the availability checks might be a bit faster, as they just check the availbility using the hexonet api, just for premium domains (when activated), also price calculations are made on php-side.
The moin point is of course the code review/cleanup and architecural review in direction of javascript.
I mean, if we already have availability check results for a certain domain name on that side, we can reuse it when switching the category for example (this is a lot faster!) and in future we can apply there further ideas like sorting by domain name, by price, by ...
JavaScript makes us a lot more flexible in direction of customer demands. That's the main point.

**Comment by papakai** [comment]
In general: if you have ideas, please address them to us. We have a list of ideas around our modules, we could add them. We are quite busy atm, but especially our WHMCS modules, I am pretty sure will improve a lot step by step.

**Comment by papakai** [comment]
fyi: I've deactivated the domain name suggestions. Now, you'll get the regular domain search mode.

**Comment by rocketdomains** [comment]
So far so good. 

As for ideas, icons for categories, sorting, price range, hexonet help find domain feature, and bulk search will be useful.

The admin side should have a "check all boxes" option to apply settings to all domains with one click.

Looking forward to seeing the admin side too.

**Comment by papakai** [comment]
@rocketdomains thanks for the input, I've added them to our list - Let us see if / when this will get realised. Some of your points are already on our list. No ETA or further details on this for now. 

> As for admin side, it's currently very cumbersome to check/uncheck hundreds of checkboxes to apply settings. Not sure if it's a whmcs issue or one related to the module. If it's module, the admin side should have a "check all boxes" option to apply settings to all domains with one click.

I expect you're talking about the domain pricing configuration page? That's part of WHMCS by default, not our module.
We just have planned to analyze how we can align the WHMCS Domain Extension configurations (Grace period, etc.) to the HEXONET system configurations. This might lead to a further new module that combines configuration data import and pricing import, maybe more. That's at least what we have planned to check. Also no ETA.
For importing prices, we already have a module, but with missing auto-synchronization.
https://github.com/hexonet/whmcs-ispapi-pricingimporter

WHMCS in the 7.7.1 already provides some bulk management there (no idea when this got introduced):
![image](https://user-images.githubusercontent.com/229425/62460538-8cf4dd80-b782-11e9-81a8-4735e4a0fd38.png)

HTH

**Comment by papakai** [comment]
Just a note: tomorrow we have a public holiday in germany. I am available on friday in case of unexpected issues.

**Comment by domainregistrar** [comment]
Tried updating to the latest version, but seems it does 3 ajax calls for
cart.php?add=.... and then shows "undefined" notice and fails to load the
fields or categories?

**Comment by papakai** [comment]
Hey @domainregistrar / Dan,

thanks for letting us know. I forgot to mention that when upgrading, one has to follow the updated [Usage Guide](https://github.com/hexonet/whmcs-ispapi-domainchecker/wiki/Usage-Guide).
Let me know if that helped.
Otherwise, be so kind to create a new github issue and to provide screenshots + logs as far as possible.

TIA!
Kai

**Comment by papakai** [comment]
@domainregistrar / Dan
I published a bugfix release 10.0.2 today that includes fixes of path names to support different setups that are based on subfolders in url. Let me know if that helps. At least the issue you described I remember to be fixed by it.

**Comment by papakai** [comment]
just for your notice guys, as this might be confusing: the order of the tlds you can apply by drag'n'drop in domainchecker's backend is **not** considered as order of the search results. It is just thought for assigning TLDs to categories, nothing else.

The order of the TLDs configured on the "Domain Pricing" section matters. There you can reorder the TLDs as desired.

**Comment by rocketdomains** [comment]
Thanks for clarifying. :-)

**Comment by papakai** [comment]
fyi: I've worked on v11.2.0 right now which targets this confusing topic.
Read: https://github.com/hexonet/whmcs-ispapi-domainchecker/wiki/FAQs#3-the-order-of-the-availability-check-results-does-not-follow-my-expectations
