### ISSUE TITLE
init.php not found in subfolder

### ISSUE THREAD

**Issue by KhensU** [hexonet/whmcs-ispapi-domainchecker#45]
in domain.php  init_path_symlink checks for the path to init.php of whmcs. If WHMCS is in a subfolder, it won't find it.

**Comment by papakai** [comment]
@KhensU 
sorry for the late reply. In general, we do not expect customers to use the symlink logic and we do not point customers on that possibility. Most of the WHMCS users are no technicians.
We internally have our module repositories checked out in folder "~/git" and symlinked accordingly, but just for development purposes.

In response to your exact case: You're right, but for technical reasons and the reasons mentioned above, we won't work on this. If you follow our [usage guide](https://github.com/hexonet/whmcs-ispapi-domainchecker/wiki/Usage-Guide), you will get it working by copying the module files accordingly.

Let me know if that helped.

**Comment by KhensU** [comment]
The only thing special about our WHMCS installation is that it is in a subfolder. We aren't using any special symlinks. The default installation of the domain checker could not find the init.php.  It was looking in the top level directory. 
We had to modify: 

$init_path_symlink = implode(DIRECTORY_SEPARATOR, array($_SERVER["DOCUMENT_ROOT"],"/c/init.php")); 

to get it to work.  (the whmcs folder is called c )

**Comment by papakai** [comment]
@KhensU thanks for the follow-up. looks like `DOCUMENT_ROOT` doesn't include the subfolder.
I will dive into this matter to check if we can roll out a generic solution.

I'll keep you posted.

**Comment by papakai** [comment]
@KhensU could you please in addition provide us the domainchecker module version and the whmcs release version you have in use? TIA!

**Comment by papakai** [comment]
@KhensU you might give release v8.2.3 a try where I reviewed the path detection.
if you're also interested in domain backordering, check also [this module](https://github.com/hexonet/whmcs-ispapi-backorder)'s latest release.

**Comment by papakai** [comment]
fixed by
https://github.com/hexonet/whmcs-ispapi-domainchecker/commit/b59eddedbdb5533ae501d5a1e2fa4bd7774c5088
